package com.wish.rd.bootstrap;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Structured Feishu alert evidence generated by {@link FeishuAlertRealSmokeTest}.
 */
record FeishuAlertEvidenceFile(
        boolean validated,
        String taskId,
        int messageCount,
        boolean metadataComplete,
        List<String> alertTypes
) {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
    private static final List<String> REQUIRED_ALERT_TYPES = FeishuAlertProductionAcceptanceReport.requiredAlertTypes()
            .stream()
            .map(Enum::name)
            .toList();

    FeishuAlertEvidenceFile {
        taskId = safe(taskId);
        messageCount = Math.max(messageCount, 0);
        alertTypes = alertTypes == null ? List.of() : List.copyOf(alertTypes);
    }

    static FeishuAlertEvidenceFile empty() {
        return new FeishuAlertEvidenceFile(false, "", 0, false, List.of());
    }

    static FeishuAlertEvidenceFile from(MultiAgentProductionAcceptanceProfile profile) {
        if (profile == null || profile.feishuAlertEvidenceJson().isBlank()) {
            return empty();
        }
        Path path = Path.of(profile.feishuAlertEvidenceJson()).toAbsolutePath().normalize();
        if (!Files.isRegularFile(path)) {
            return empty();
        }
        try {
            JsonNode root = OBJECT_MAPPER.readTree(path.toFile());
            List<String> alertTypes = values(root.path("alertTypes"));
            int messageCount = root.path("feishuAlertMessageCount").asInt(0);
            List<String> messageIds = values(root.path("messageIds"));
            boolean sameRun = profile.rdBotVersion().equals(root.path("rdBotVersion").asText(""))
                    && profile.environmentId().equals(root.path("environmentId").asText(""))
                    && profile.executedBy().equals(root.path("executedBy").asText(""));
            String taskId = commonRequiredDeliveryTaskId(root.path("deliveries"));
            String feishuAlertTaskId = root.path("feishuAlertTaskId").asText("").strip();
            boolean metadataComplete = deliveryMetadataComplete(root.path("deliveries"))
                    && !taskId.isBlank()
                    && taskId.equals(feishuAlertTaskId);
            boolean validated = root.path("feishuAlertEvidenceValidated").asBoolean(false)
                    && root.path("feishuAlertMetadataComplete").asBoolean(false)
                    && sameRun
                    && messageCount >= REQUIRED_ALERT_TYPES.size()
                    && messageIds.size() >= REQUIRED_ALERT_TYPES.size()
                    && messageIdsMatchDeliveries(messageIds, root.path("deliveries"))
                    && alertTypes.containsAll(REQUIRED_ALERT_TYPES)
                    && metadataComplete;
            return validated ? new FeishuAlertEvidenceFile(true, taskId, messageCount, true, alertTypes) : empty();
        } catch (RuntimeException | java.io.IOException ignored) {
            return empty();
        }
    }

    private static String commonRequiredDeliveryTaskId(JsonNode deliveries) {
        if (!deliveries.isArray()) {
            return "";
        }
        java.util.HashSet<String> coveredTypes = new java.util.HashSet<>();
        String taskId = "";
        for (JsonNode delivery : deliveries) {
            String alertType = delivery.path("alertType").asText("").strip();
            if (!REQUIRED_ALERT_TYPES.contains(alertType)) {
                continue;
            }
            String deliveryTaskId = delivery.path("taskId").asText("").strip();
            if (deliveryTaskId.isBlank()) {
                return "";
            }
            if (taskId.isBlank()) {
                taskId = deliveryTaskId;
            } else if (!taskId.equals(deliveryTaskId)) {
                return "";
            }
            coveredTypes.add(alertType);
        }
        return coveredTypes.containsAll(REQUIRED_ALERT_TYPES) ? taskId : "";
    }

    private static boolean deliveryMetadataComplete(JsonNode deliveries) {
        if (!deliveries.isArray() || deliveries.size() < REQUIRED_ALERT_TYPES.size()) {
            return false;
        }
        java.util.HashSet<String> coveredTypes = new java.util.HashSet<>();
        for (JsonNode delivery : deliveries) {
            String alertType = delivery.path("alertType").asText("").strip();
            if (!REQUIRED_ALERT_TYPES.contains(alertType)) {
                continue;
            }
            if (!delivery.path("delivered").asBoolean(false)
                    || blank(delivery, "messageId")
                    || blank(delivery, "taskId")
                    || blank(delivery, "role")
                    || blank(delivery, "stageRunId")
                    || blank(delivery, "failureCategory")
                    || blank(delivery, "nextAction")
                    || !productionArtifactUri(delivery.path("artifactUrl").asText(""))) {
                return false;
            }
            if (!alertType.equals(delivery.path("failureCategory").asText("").strip())) {
                return false;
            }
            coveredTypes.add(alertType);
        }
        return coveredTypes.containsAll(REQUIRED_ALERT_TYPES);
    }

    private static boolean messageIdsMatchDeliveries(List<String> messageIds, JsonNode deliveries) {
        if (!deliveries.isArray()) {
            return false;
        }
        java.util.HashSet<String> topLevelMessageIds = new java.util.HashSet<>(messageIds);
        java.util.HashSet<String> deliveryMessageIds = new java.util.HashSet<>();
        for (JsonNode delivery : deliveries) {
            String alertType = delivery.path("alertType").asText("").strip();
            String messageId = delivery.path("messageId").asText("").strip();
            if (REQUIRED_ALERT_TYPES.contains(alertType) && !messageId.isBlank()) {
                deliveryMessageIds.add(messageId);
            }
        }
        return deliveryMessageIds.size() >= REQUIRED_ALERT_TYPES.size()
                && topLevelMessageIds.containsAll(deliveryMessageIds);
    }

    private static boolean blank(JsonNode node, String fieldName) {
        return node.path(fieldName).asText("").strip().isBlank();
    }

    private static boolean productionArtifactUri(String value) {
        return ProductionEvidenceUris.isProductionArtifactUri(value);
    }

    private static String safe(String value) {
        return value == null ? "" : value.strip();
    }

    private static List<String> values(JsonNode node) {
        if (!node.isArray()) {
            return List.of();
        }
        java.util.ArrayList<String> values = new java.util.ArrayList<>();
        node.forEach(item -> {
            String value = item.asText("").strip();
            if (!value.isBlank()) {
                values.add(value);
            }
        });
        return List.copyOf(values);
    }
}
