package com.wish.rd.bootstrap;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.wish.rd.bootstrap.github.impl.GitHubCodePlatformAdapter;
import com.wish.rd.bootstrap.github.GitHubCodePlatformProperties;
import com.wish.rd.bootstrap.github.impl.MockGitHubCodePlatformAdapter;
import com.wish.rd.engine.merge.model.PullRequestMergeStatus;
import com.wish.rd.exec.repair.code.CodePlatformPort;
import com.wish.rd.exec.repair.code.model.BranchHeadResult;
import com.wish.rd.exec.repair.code.model.CreatePullRequestCommand;
import com.wish.rd.exec.repair.code.model.FindBranchHeadCommand;
import com.wish.rd.exec.repair.code.model.FindOpenPullRequestCommand;
import com.wish.rd.exec.repair.code.model.PullRequestResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyPairGenerator;
import java.security.interfaces.RSAPrivateCrtKey;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class GitHubCodePlatformAdapterTest {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    @TempDir
    Path temporaryDirectory;

    @Test
    void shouldSelectMockAdapterByDefaultForZeroConfigStartup() {
        ApplicationContextRunner contextRunner = new ApplicationContextRunner()
                .withUserConfiguration(GitHubAdapterContextConfiguration.class);

        contextRunner.run(context -> {
            assertEquals(1, context.getBeanNamesForType(CodePlatformPort.class).length);
            assertTrue(context.getBean(CodePlatformPort.class) instanceof MockGitHubCodePlatformAdapter);
        });
    }

    @Test
    void mockAdapterShouldReturnDeterministicPullRequestUrl() {
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setWebBaseUrl("https://github.example.local");
        MockGitHubCodePlatformAdapter adapter = new MockGitHubCodePlatformAdapter(properties);

        PullRequestResult result = adapter.createPullRequest(command("acme", "order"));

        assertEquals("https://github.example.local/acme/order/pull/repair-task-1001", result.pullRequestUrl());
        assertEquals("mock", result.metadata().get("provider"));
        assertEquals("acme/order", result.metadata().get("repository"));
    }

    @Test
    void realAdapterShouldRejectNonAllowlistedRepositoryBeforeHttpCall() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/catalog"));
        RecordingSender sender = new RecordingSender(successfulPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        assertThrows(IllegalArgumentException.class, () -> adapter.createPullRequest(command("acme", "order")));

        assertTrue(sender.requests().isEmpty());
    }

    @Test
    void realAdapterShouldBuildCreatePullRequestRequestWithoutNetworkInTests() throws IOException {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/order"));
        RecordingSender sender = new RecordingSender(successfulPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        PullRequestResult result = adapter.createPullRequest(command("acme", "order"));

        assertEquals("https://github.example.local/acme/order/pull/42", result.pullRequestUrl());
        assertEquals("42", result.pullRequestNumber());
        assertEquals(1, sender.requests().size());
        GitHubCodePlatformAdapter.GitHubHttpRequest request = sender.requests().getFirst();
        assertEquals("POST", request.method());
        assertEquals("https://api.github.example.local/repos/acme/order/pulls", request.url());
        assertEquals("application/vnd.github+json", request.headers().get("Accept"));
        assertEquals("Bearer", request.headers().get("Authorization").split(" ")[0]);
        assertFalse(request.toString().contains("ghp-local-smoke"));

        JsonNode body = OBJECT_MAPPER.readTree(request.body());
        assertEquals("Fix order failure", body.path("title").asText());
        assertEquals("repair/task-1001", body.path("head").asText());
        assertEquals("main", body.path("base").asText());
        assertEquals("Generated by RD-Bot repair executor.", body.path("body").asText());
        assertFalse(request.body().contains("Feishu"));
    }

    @Test
    void shouldFindOpenPullRequestByHeadAndBaseWithoutNetworkInTests() throws IOException {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/order"));
        RecordingSender sender = new RecordingSender("""
                [{
                  "html_url":"https://github.example.local/acme/order/pull/77",
                  "number":77,
                  "body":"- taskId: task-1001\\n- operationId: sha256:abc",
                  "head":{"sha":"deadbeef"}
                }]
                """);
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        Optional<PullRequestResult> found = adapter.findOpenPullRequest(new FindOpenPullRequestCommand(
                "acme", "order", "main", "requirement/task-1001"
        ));

        assertTrue(found.isPresent());
        assertEquals("https://github.example.local/acme/order/pull/77", found.orElseThrow().pullRequestUrl());
        assertEquals("77", found.orElseThrow().pullRequestNumber());
        assertEquals("deadbeef", found.orElseThrow().metadata().get("headSha"));
        assertTrue(found.orElseThrow().metadata().get("body").contains("operationId"));
        assertEquals(1, sender.requests().size());
        GitHubCodePlatformAdapter.GitHubHttpRequest request = sender.requests().getFirst();
        assertEquals("GET", request.method());
        assertTrue(request.url().startsWith("https://api.github.example.local/repos/acme/order/pulls?"));
        assertTrue(request.url().contains("state=open"));
        assertTrue(request.url().contains("head=acme%3Arequirement%2Ftask-1001")
                || request.url().contains("head=" + java.net.URLEncoder.encode(
                        "acme:requirement/task-1001", java.nio.charset.StandardCharsets.UTF_8)));
        assertTrue(request.url().contains("base=main"));
    }

    @Test
    void shouldReturnEmptyWhenNoOpenPullRequestMatchesHeadAndBase() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/order"));
        RecordingSender sender = new RecordingSender("[]");
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        Optional<PullRequestResult> found = adapter.findOpenPullRequest(new FindOpenPullRequestCommand(
                "acme", "order", "main", "requirement/task-1001"
        ));

        assertTrue(found.isEmpty());
        assertEquals(1, sender.requests().size());
    }

    @Test
    void shouldFindBranchHeadWithoutNetworkInTests() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/order"));
        RecordingSender sender = new RecordingSender("""
                {
                  "ref":"refs/heads/requirement/task-1001",
                  "object":{"sha":"cafebabe0123456789","type":"commit"}
                }
                """);
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        Optional<BranchHeadResult> found = adapter.findBranchHead(new FindBranchHeadCommand(
                "acme", "order", "requirement/task-1001"
        ));

        assertTrue(found.isPresent());
        assertEquals("cafebabe0123456789", found.orElseThrow().commitSha());
        assertEquals("requirement/task-1001", found.orElseThrow().metadata().get("branch"));
        assertEquals(1, sender.requests().size());
        GitHubCodePlatformAdapter.GitHubHttpRequest request = sender.requests().getFirst();
        assertEquals("GET", request.method());
        assertTrue(request.url().contains("/repos/acme/order/git/ref/heads/"));
        assertTrue(request.url().contains("requirement%2Ftask-1001")
                || request.url().contains("requirement/task-1001"));
    }

    @Test
    void shouldReturnEmptyWhenBranchHeadIsMissing() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/order"));
        RecordingSender sender = new RecordingSender(404, "{}");
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        Optional<BranchHeadResult> found = adapter.findBranchHead(new FindBranchHeadCommand(
                "acme", "order", "requirement/missing"
        ));

        assertTrue(found.isEmpty());
        assertEquals(1, sender.requests().size());
    }

    @Test
    void realAdapterShouldReadPullRequestMergedStatusWithoutNetworkInTests() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/order"));
        RecordingSender sender = new RecordingSender(mergedPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        PullRequestMergeStatus status = adapter.findByUrl("https://github.example.local/acme/order/pull/42");

        assertTrue(status.merged());
        assertEquals("closed", status.state());
        assertEquals("acme/order", status.repository());
        assertEquals("42", status.pullRequestNumber());
        assertEquals(1, sender.requests().size());
        GitHubCodePlatformAdapter.GitHubHttpRequest request = sender.requests().getFirst();
        assertEquals("GET", request.method());
        assertEquals("https://api.github.example.local/repos/acme/order/pulls/42", request.url());
        assertEquals("", request.body());
    }

    @Test
    void realAdapterShouldRejectNonAllowlistedPullRequestStatusRepositoryBeforeHttpCall() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/catalog"));
        RecordingSender sender = new RecordingSender(mergedPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        assertThrows(IllegalArgumentException.class,
                () -> adapter.findByUrl("https://github.example.local/acme/order/pull/42"));

        assertTrue(sender.requests().isEmpty());
    }

    @Test
    void patLocalSmokeModeShouldRequireTokenAndNameItExplicitly() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setPatToken(" ");

        IllegalStateException exception = assertThrows(
                IllegalStateException.class,
                () -> new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, new RecordingSender(successfulPullResponse()))
                        .createPullRequest(command("acme", "order"))
        );

        assertTrue(exception.getMessage().contains("PAT local smoke"));
    }

    @Test
    void githubAppModeShouldRequireProductionCredentials() {
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.GITHUB_APP);
        properties.setAllowedRepositories(List.of("acme/order"));

        IllegalStateException exception = assertThrows(
                IllegalStateException.class,
                () -> new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, new RecordingSender(successfulPullResponse()))
                        .createPullRequest(command("acme", "order"))
        );

        assertTrue(exception.getMessage().contains("GitHub App"));
        assertTrue(exception.getMessage().contains("appId"));
        assertTrue(exception.getMessage().contains("installationId"));
        assertTrue(exception.getMessage().contains("privateKeyRef"));
    }

    @Test
    void ghCliLocalSmokeModeShouldCreatePullRequestWithoutPatToken() throws IOException {
        GitHubCodePlatformProperties properties = realGhCliProperties();
        properties.setPatToken(" ");
        RecordingSender sender = new RecordingSender(successfulPullResponse());
        RecordingCliRunner cliRunner = new RecordingCliRunner(successfulPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(
                properties,
                OBJECT_MAPPER,
                sender,
                cliRunner
        );

        PullRequestResult result = adapter.createPullRequest(command("acme", "order"));

        assertEquals("https://github.example.local/acme/order/pull/42", result.pullRequestUrl());
        assertEquals("42", result.pullRequestNumber());
        assertTrue(sender.requests().isEmpty());
        assertEquals(1, cliRunner.commands().size());
        List<String> command = cliRunner.commands().getFirst();
        assertEquals(List.of(
                "gh",
                "api",
                "repos/acme/order/pulls",
                "--method",
                "POST",
                "-f",
                "title=Fix order failure",
                "-f",
                "head=repair/task-1001",
                "-f",
                "base=main",
                "-f",
                "body=Generated by RD-Bot repair executor."
        ), command);
        assertFalse(String.join(" ", command).contains("ghp-local-smoke"));
    }

    @Test
    void ghCliLocalSmokeModeShouldReadPullRequestMergedStatusWithoutPatToken() {
        GitHubCodePlatformProperties properties = realGhCliProperties();
        properties.setPatToken(" ");
        RecordingSender sender = new RecordingSender(mergedPullResponse());
        RecordingCliRunner cliRunner = new RecordingCliRunner(mergedPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(
                properties,
                OBJECT_MAPPER,
                sender,
                cliRunner
        );

        PullRequestMergeStatus status = adapter.findByUrl("https://github.example.local/acme/order/pull/42");

        assertTrue(status.merged());
        assertEquals("closed", status.state());
        assertEquals("acme/order", status.repository());
        assertEquals("42", status.pullRequestNumber());
        assertTrue(sender.requests().isEmpty());
        assertEquals(List.of("gh", "api", "repos/acme/order/pulls/42"), cliRunner.commands().getFirst());
    }

    @Test
    void ghCliLocalSmokeModeShouldReadPullRequestMergedStatusFromMarkdownLink() {
        GitHubCodePlatformProperties properties = realGhCliProperties();
        properties.setPatToken(" ");
        RecordingSender sender = new RecordingSender(mergedPullResponse());
        RecordingCliRunner cliRunner = new RecordingCliRunner(mergedPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(
                properties,
                OBJECT_MAPPER,
                sender,
                cliRunner
        );

        PullRequestMergeStatus status = adapter.findByUrl(
                "[acme/order#42](https://github.example.local/acme/order/pull/42)"
        );

        assertTrue(status.merged());
        assertEquals("acme/order", status.repository());
        assertEquals("42", status.pullRequestNumber());
        assertTrue(sender.requests().isEmpty());
        assertEquals(List.of("gh", "api", "repos/acme/order/pulls/42"), cliRunner.commands().getFirst());
    }

    @Test
    void githubAppModeShouldReadPkcs1PrivateKeyReferenceAndRedactBearerTokens() throws Exception {
        Path privateKey = temporaryDirectory.resolve("github-app-private-key.pem");
        Files.writeString(privateKey, generatedPkcs1PrivateKeyPem(), StandardCharsets.UTF_8);
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.GITHUB_APP);
        properties.setApiBaseUrl("https://api.github.example.local");
        properties.setAllowedRepositories(List.of("acme/order"));
        properties.setAppId("12345");
        properties.setInstallationId("98765");
        properties.setPrivateKeyRef(privateKey.toString());
        RecordingSender sender = new RecordingSender(installationTokenResponse(), successfulPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        PullRequestResult result = adapter.createPullRequest(command("acme", "order"));

        assertEquals("https://github.example.local/acme/order/pull/42", result.pullRequestUrl());
        assertEquals(2, sender.requests().size());
        GitHubCodePlatformAdapter.GitHubHttpRequest tokenRequest = sender.requests().getFirst();
        assertEquals("https://api.github.example.local/app/installations/98765/access_tokens", tokenRequest.url());
        assertEquals("Bearer", tokenRequest.headers().get("Authorization").split(" ")[0]);
        assertFalse(tokenRequest.toString().contains(tokenRequest.headers().get("Authorization")));
        GitHubCodePlatformAdapter.GitHubHttpRequest pullRequest = sender.requests().get(1);
        assertEquals("Bearer", pullRequest.headers().get("Authorization").split(" ")[0]);
        assertFalse(pullRequest.toString().contains("installation-token"));
    }

    @Test
    void githubAppModeShouldRejectInlinePrivateKeyRefWithoutEchoingPrivateKey() {
        String inlinePrivateKey = """
                -----BEGIN RSA PRIVATE KEY-----
                not-a-real-key
                -----END RSA PRIVATE KEY-----
                """;
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.GITHUB_APP);
        properties.setAllowedRepositories(List.of("acme/order"));
        properties.setAppId("12345");
        properties.setInstallationId("98765");
        properties.setPrivateKeyRef(inlinePrivateKey);

        IllegalStateException exception = assertThrows(
                IllegalStateException.class,
                () -> new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, new RecordingSender(installationTokenResponse()))
                        .createPullRequest(command("acme", "order"))
        );

        assertTrue(exception.getMessage().contains("privateKeyRef"));
        assertFalse(exception.getMessage().contains("BEGIN RSA PRIVATE KEY"));
        assertFalse(exception.getMessage().contains("not-a-real-key"));
    }

    @Test
    void sourceShouldNotKnowFeishuTicketFields() throws IOException {
        String adapterSource = java.nio.file.Files.readString(moduleRoot().resolve(
                "src/main/java/com/wish/rd/bootstrap/github/impl/GitHubCodePlatformAdapter.java"));

        assertFalse(adapterSource.toLowerCase().contains("feishu"));
        assertFalse(adapterSource.contains("helpdesk"));
        assertFalse(adapterSource.contains("ticketStatus"));
    }

    private static GitHubCodePlatformProperties realPatProperties() {
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.PAT_LOCAL_SMOKE);
        properties.setApiBaseUrl("https://api.github.example.local");
        properties.setWebBaseUrl("https://github.example.local");
        properties.setPatToken("ghp-local-smoke");
        return properties;
    }

    private static GitHubCodePlatformProperties realGhCliProperties() {
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.GH_CLI_LOCAL_SMOKE);
        properties.setAllowedRepositories(List.of("acme/order"));
        properties.setApiBaseUrl("https://api.github.example.local");
        properties.setWebBaseUrl("https://github.example.local");
        return properties;
    }

    private static CreatePullRequestCommand command(String owner, String repo) {
        return new CreatePullRequestCommand(
                owner,
                repo,
                "main",
                "repair/task-1001",
                "Fix order failure",
                "Generated by RD-Bot repair executor.",
                List.of(),
                Map.of("taskId", "task-1001")
        );
    }

    private static String successfulPullResponse() {
        return """
                {
                  "html_url": "https://github.example.local/acme/order/pull/42",
                  "number": 42,
                  "head": {"sha": "abc123"}
                }
                """;
    }

    private static String mergedPullResponse() {
        return """
                {
                  "html_url": "https://github.example.local/acme/order/pull/42",
                  "number": 42,
                  "state": "closed",
                  "merged": true,
                  "head": {"sha": "abc123"}
                }
                """;
    }

    private static String installationTokenResponse() {
        return """
                {
                  "token": "installation-token"
                }
                """;
    }

    private static String generatedPkcs1PrivateKeyPem() throws Exception {
        KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
        generator.initialize(2048);
        RSAPrivateCrtKey key = (RSAPrivateCrtKey) generator.generateKeyPair().getPrivate();
        byte[] pkcs1 = derSequence(
                derInteger(java.math.BigInteger.ZERO),
                derInteger(key.getModulus()),
                derInteger(key.getPublicExponent()),
                derInteger(key.getPrivateExponent()),
                derInteger(key.getPrimeP()),
                derInteger(key.getPrimeQ()),
                derInteger(key.getPrimeExponentP()),
                derInteger(key.getPrimeExponentQ()),
                derInteger(key.getCrtCoefficient())
        );
        return "-----BEGIN RSA PRIVATE KEY-----\n"
                + java.util.Base64.getMimeEncoder(64, "\n".getBytes(StandardCharsets.US_ASCII)).encodeToString(pkcs1)
                + "\n-----END RSA PRIVATE KEY-----\n";
    }

    private static byte[] derSequence(byte[]... entries) {
        int length = 0;
        for (byte[] entry : entries) {
            length += entry.length;
        }
        return derValue(0x30, concat(entries, length));
    }

    private static byte[] derInteger(java.math.BigInteger value) {
        return derValue(0x02, value.toByteArray());
    }

    private static byte[] derValue(int tag, byte[] body) {
        byte[] length = derLength(body.length);
        byte[] result = new byte[1 + length.length + body.length];
        result[0] = (byte) tag;
        System.arraycopy(length, 0, result, 1, length.length);
        System.arraycopy(body, 0, result, 1 + length.length, body.length);
        return result;
    }

    private static byte[] derLength(int length) {
        if (length < 128) {
            return new byte[]{(byte) length};
        }
        int bytes = 0;
        int value = length;
        while (value > 0) {
            bytes++;
            value >>= 8;
        }
        byte[] encoded = new byte[1 + bytes];
        encoded[0] = (byte) (0x80 | bytes);
        for (int index = bytes; index > 0; index--) {
            encoded[index] = (byte) (length & 0xff);
            length >>= 8;
        }
        return encoded;
    }

    private static byte[] concat(byte[][] entries, int length) {
        byte[] result = new byte[length];
        int offset = 0;
        for (byte[] entry : entries) {
            System.arraycopy(entry, 0, result, offset, entry.length);
            offset += entry.length;
        }
        return result;
    }

    private static java.nio.file.Path moduleRoot() {
        java.nio.file.Path current = java.nio.file.Path.of(System.getProperty("user.dir")).toAbsolutePath().normalize();
        if (current.getFileName() != null && "bootstrap".equals(current.getFileName().toString())) {
            return current;
        }
        return current.resolve("bootstrap");
    }

    private static final class RecordingSender implements GitHubCodePlatformAdapter.GitHubRequestSender {

        private final List<String> responseBodies;
        private final int statusCode;
        private final List<GitHubCodePlatformAdapter.GitHubHttpRequest> requests = new java.util.ArrayList<>();

        private RecordingSender(String... responseBodies) {
            this(201, responseBodies);
        }

        private RecordingSender(int statusCode, String... responseBodies) {
            this.statusCode = statusCode;
            this.responseBodies = List.of(responseBodies);
        }

        @Override
        public GitHubCodePlatformAdapter.GitHubHttpResponse send(GitHubCodePlatformAdapter.GitHubHttpRequest request) {
            int responseIndex = Math.min(requests.size(), responseBodies.size() - 1);
            requests.add(request);
            return new GitHubCodePlatformAdapter.GitHubHttpResponse(statusCode, responseBodies.get(responseIndex));
        }

        private List<GitHubCodePlatformAdapter.GitHubHttpRequest> requests() {
            return List.copyOf(requests);
        }
    }

    private static final class RecordingCliRunner implements GitHubCodePlatformAdapter.GitHubCliRunner {

        private final List<String> responseBodies;
        private final List<List<String>> commands = new java.util.ArrayList<>();

        private RecordingCliRunner(String... responseBodies) {
            this.responseBodies = List.of(responseBodies);
        }

        @Override
        public GitHubCodePlatformAdapter.GitHubCliResult run(List<String> command) {
            int responseIndex = Math.min(commands.size(), responseBodies.size() - 1);
            commands.add(List.copyOf(command));
            return new GitHubCodePlatformAdapter.GitHubCliResult(0, responseBodies.get(responseIndex), "");
        }

        private List<List<String>> commands() {
            return List.copyOf(commands);
        }
    }

    @Configuration
    @Import({
            GitHubCodePlatformProperties.class,
            MockGitHubCodePlatformAdapter.class,
            GitHubCodePlatformAdapter.class
    })
    static class GitHubAdapterContextConfiguration {
    }
}
