package com.wish.rd.bootstrap;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Structured evidence generated by {@link GitHubPullRequestRemoteEvidenceRealSmokeTest}.
 */
record GitHubPrRemoteEvidenceFile(
        boolean validated,
        String taskId,
        String pullRequestUrl,
        String pullRequestNumber,
        String baseBranch,
        String workBranch,
        boolean pullRequestBodyIncludesDeliveryReview,
        boolean pullRequestBodyIncludesQaEvidence,
        boolean pullRequestBodyContainsTaskId,
        boolean pullRequestBodyContainsArtifactLink,
        boolean secretScanEvidenceValidated,
        boolean secretLeakFound,
        int secretScannedValueCount
) {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    GitHubPrRemoteEvidenceFile {
        taskId = safe(taskId);
        pullRequestUrl = safe(pullRequestUrl);
        pullRequestNumber = safe(pullRequestNumber);
        baseBranch = safe(baseBranch);
        workBranch = safe(workBranch);
        secretScannedValueCount = Math.max(secretScannedValueCount, 0);
    }

    static GitHubPrRemoteEvidenceFile empty() {
        return new GitHubPrRemoteEvidenceFile(
                false,
                "",
                "",
                "",
                "",
                "",
                false,
                false,
                false,
                false,
                false,
                false,
                0
        );
    }

    static GitHubPrRemoteEvidenceFile from(MultiAgentProductionAcceptanceProfile profile) {
        if (profile == null || profile.githubPrRemoteEvidenceJson().isBlank()) {
            return empty();
        }
        Path path = Path.of(profile.githubPrRemoteEvidenceJson()).toAbsolutePath().normalize();
        if (!Files.isRegularFile(path)) {
            return empty();
        }
        try {
            JsonNode root = OBJECT_MAPPER.readTree(path.toFile());
            String taskId = root.path("taskId").asText("");
            String pullRequestUrl = root.path("pullRequestUrl").asText("");
            String pullRequestNumber = root.path("pullRequestNumber").asText("");
            String baseBranch = root.path("baseBranch").asText("");
            String workBranch = root.path("workBranch").asText("");
            int secretScannedValueCount = root.path("secretScannedValueCount").asInt(0);
            boolean sameRun = profile.rdBotVersion().equals(root.path("rdBotVersion").asText(""))
                    && profile.environmentId().equals(root.path("environmentId").asText(""))
                    && profile.executedBy().equals(root.path("executedBy").asText(""));
            boolean validated = root.path("githubPrRemoteEvidenceValidated").asBoolean(false)
                    && root.path("remotePrTraceValidated").asBoolean(false)
                    && sameRun
                    && pullRequestRepositoryMatches(pullRequestUrl, pullRequestNumber, profile)
                    && profile.baseBranch().equals(baseBranch)
                    && workBranchMatchesTaskBranch(workBranch, taskId)
                    && root.path("pullRequestBodyIncludesDeliveryReview").asBoolean(false)
                    && root.path("pullRequestBodyIncludesQaEvidence").asBoolean(false)
                    && root.path("pullRequestBodyContainsTaskId").asBoolean(false)
                    && root.path("pullRequestBodyContainsExactTaskId").asBoolean(false)
                    && root.path("pullRequestBodyContainsArtifactLink").asBoolean(false)
                    && root.path("secretScanEvidenceValidated").asBoolean(false)
                    && !root.path("secretLeakFound").asBoolean(true)
                    && secretScannedValueCount > 0;
            return validated ? new GitHubPrRemoteEvidenceFile(
                    true,
                    taskId,
                    pullRequestUrl,
                    pullRequestNumber,
                    baseBranch,
                    workBranch,
                    true,
                    true,
                    true,
                    true,
                    true,
                    false,
                    secretScannedValueCount
            ) : empty();
        } catch (RuntimeException | java.io.IOException ignored) {
            return empty();
        }
    }

    MultiAgentProductionAcceptanceReport.GitHubPrRemoteEvidence toReportEvidence() {
        if (!validated) {
            return MultiAgentProductionAcceptanceReport.GitHubPrRemoteEvidence.empty();
        }
        return new MultiAgentProductionAcceptanceReport.GitHubPrRemoteEvidence(
                true,
                taskId,
                pullRequestUrl,
                pullRequestNumber,
                baseBranch,
                workBranch,
                pullRequestBodyIncludesDeliveryReview,
                pullRequestBodyIncludesQaEvidence,
                pullRequestBodyContainsTaskId,
                pullRequestBodyContainsArtifactLink,
                secretScanEvidenceValidated,
                secretLeakFound,
                secretScannedValueCount
        );
    }

    private static boolean pullRequestRepositoryMatches(
            String pullRequestUrl,
            String pullRequestNumber,
            MultiAgentProductionAcceptanceProfile profile
    ) {
        String safePullRequestUrl = safe(pullRequestUrl);
        String safePullRequestNumber = safe(pullRequestNumber);
        if (safePullRequestUrl.isBlank() || safePullRequestNumber.isBlank()) {
            return false;
        }
        try {
            URI uri = URI.create(safePullRequestUrl);
            URI repositoryUri = URI.create(safe(profile.repositoryUrl()));
            String path = safe(uri.getPath()).toLowerCase(java.util.Locale.ROOT);
            String pullRequestHost = safe(uri.getHost()).toLowerCase(java.util.Locale.ROOT);
            String repositoryHost = safe(repositoryUri.getHost()).toLowerCase(java.util.Locale.ROOT);
            String expectedPath = "/" + safe(profile.repoOwner()).toLowerCase(java.util.Locale.ROOT)
                    + "/" + safe(profile.repoName()).toLowerCase(java.util.Locale.ROOT)
                    + "/pull/"
                    + safePullRequestNumber;
            return uri.isAbsolute()
                    && isHttpOrHttps(uri)
                    && !repositoryHost.isBlank()
                    && pullRequestHost.equals(repositoryHost)
                    && path.equals(expectedPath);
        } catch (RuntimeException ignored) {
            return false;
        }
    }

    private static boolean isHttpOrHttps(URI uri) {
        String scheme = safe(uri.getScheme()).toLowerCase(java.util.Locale.ROOT);
        return "http".equals(scheme) || "https".equals(scheme);
    }

    private static boolean workBranchMatchesTaskBranch(String workBranch, String taskId) {
        String safeTaskId = safe(taskId);
        return !safeTaskId.isBlank() && ("requirement/" + safeTaskId).equals(safe(workBranch));
    }

    private static String safe(String value) {
        return value == null ? "" : value.strip();
    }
}
