package com.wish.rd.bootstrap;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.wish.rd.bootstrap.github.GitHubCodePlatformAdapter;
import com.wish.rd.bootstrap.github.GitHubCodePlatformProperties;
import com.wish.rd.bootstrap.github.MockGitHubCodePlatformAdapter;
import com.wish.rd.exec.repair.code.CodePlatformPort;
import com.wish.rd.exec.repair.code.CreatePullRequestCommand;
import com.wish.rd.exec.repair.code.PullRequestResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyPairGenerator;
import java.security.interfaces.RSAPrivateCrtKey;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class GitHubCodePlatformAdapterTest {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    @TempDir
    Path temporaryDirectory;

    @Test
    void shouldSelectMockAdapterByDefaultForZeroConfigStartup() {
        ApplicationContextRunner contextRunner = new ApplicationContextRunner()
                .withUserConfiguration(GitHubAdapterContextConfiguration.class);

        contextRunner.run(context -> {
            assertEquals(1, context.getBeanNamesForType(CodePlatformPort.class).length);
            assertTrue(context.getBean(CodePlatformPort.class) instanceof MockGitHubCodePlatformAdapter);
        });
    }

    @Test
    void mockAdapterShouldReturnDeterministicPullRequestUrl() {
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setWebBaseUrl("https://github.example.local");
        MockGitHubCodePlatformAdapter adapter = new MockGitHubCodePlatformAdapter(properties);

        PullRequestResult result = adapter.createPullRequest(command("acme", "order"));

        assertEquals("https://github.example.local/acme/order/pull/repair-task-1001", result.pullRequestUrl());
        assertEquals("mock", result.metadata().get("provider"));
        assertEquals("acme/order", result.metadata().get("repository"));
    }

    @Test
    void realAdapterShouldRejectNonAllowlistedRepositoryBeforeHttpCall() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/catalog"));
        RecordingSender sender = new RecordingSender(successfulPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        assertThrows(IllegalArgumentException.class, () -> adapter.createPullRequest(command("acme", "order")));

        assertTrue(sender.requests().isEmpty());
    }

    @Test
    void realAdapterShouldBuildCreatePullRequestRequestWithoutNetworkInTests() throws IOException {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setAllowedRepositories(List.of("acme/order"));
        RecordingSender sender = new RecordingSender(successfulPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        PullRequestResult result = adapter.createPullRequest(command("acme", "order"));

        assertEquals("https://github.example.local/acme/order/pull/42", result.pullRequestUrl());
        assertEquals("42", result.pullRequestNumber());
        assertEquals(1, sender.requests().size());
        GitHubCodePlatformAdapter.GitHubHttpRequest request = sender.requests().getFirst();
        assertEquals("POST", request.method());
        assertEquals("https://api.github.example.local/repos/acme/order/pulls", request.url());
        assertEquals("application/vnd.github+json", request.headers().get("Accept"));
        assertEquals("Bearer", request.headers().get("Authorization").split(" ")[0]);
        assertFalse(request.toString().contains("ghp-local-smoke"));

        JsonNode body = OBJECT_MAPPER.readTree(request.body());
        assertEquals("Fix order failure", body.path("title").asText());
        assertEquals("repair/task-1001", body.path("head").asText());
        assertEquals("main", body.path("base").asText());
        assertEquals("Generated by RD-Bot repair executor.", body.path("body").asText());
        assertFalse(request.body().contains("Feishu"));
    }

    @Test
    void patLocalSmokeModeShouldRequireTokenAndNameItExplicitly() {
        GitHubCodePlatformProperties properties = realPatProperties();
        properties.setPatToken(" ");

        IllegalStateException exception = assertThrows(
                IllegalStateException.class,
                () -> new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, new RecordingSender(successfulPullResponse()))
                        .createPullRequest(command("acme", "order"))
        );

        assertTrue(exception.getMessage().contains("PAT local smoke"));
    }

    @Test
    void githubAppModeShouldRequireProductionCredentials() {
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.GITHUB_APP);
        properties.setAllowedRepositories(List.of("acme/order"));

        IllegalStateException exception = assertThrows(
                IllegalStateException.class,
                () -> new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, new RecordingSender(successfulPullResponse()))
                        .createPullRequest(command("acme", "order"))
        );

        assertTrue(exception.getMessage().contains("GitHub App"));
        assertTrue(exception.getMessage().contains("appId"));
        assertTrue(exception.getMessage().contains("installationId"));
        assertTrue(exception.getMessage().contains("privateKeyRef"));
    }

    @Test
    void githubAppModeShouldReadPkcs1PrivateKeyReferenceAndRedactBearerTokens() throws Exception {
        Path privateKey = temporaryDirectory.resolve("github-app-private-key.pem");
        Files.writeString(privateKey, generatedPkcs1PrivateKeyPem(), StandardCharsets.UTF_8);
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.GITHUB_APP);
        properties.setApiBaseUrl("https://api.github.example.local");
        properties.setAllowedRepositories(List.of("acme/order"));
        properties.setAppId("12345");
        properties.setInstallationId("98765");
        properties.setPrivateKeyRef(privateKey.toString());
        RecordingSender sender = new RecordingSender(installationTokenResponse(), successfulPullResponse());
        GitHubCodePlatformAdapter adapter = new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, sender);

        PullRequestResult result = adapter.createPullRequest(command("acme", "order"));

        assertEquals("https://github.example.local/acme/order/pull/42", result.pullRequestUrl());
        assertEquals(2, sender.requests().size());
        GitHubCodePlatformAdapter.GitHubHttpRequest tokenRequest = sender.requests().getFirst();
        assertEquals("https://api.github.example.local/app/installations/98765/access_tokens", tokenRequest.url());
        assertEquals("Bearer", tokenRequest.headers().get("Authorization").split(" ")[0]);
        assertFalse(tokenRequest.toString().contains(tokenRequest.headers().get("Authorization")));
        GitHubCodePlatformAdapter.GitHubHttpRequest pullRequest = sender.requests().get(1);
        assertEquals("Bearer", pullRequest.headers().get("Authorization").split(" ")[0]);
        assertFalse(pullRequest.toString().contains("installation-token"));
    }

    @Test
    void githubAppModeShouldRejectInlinePrivateKeyRefWithoutEchoingPrivateKey() {
        String inlinePrivateKey = """
                -----BEGIN RSA PRIVATE KEY-----
                not-a-real-key
                -----END RSA PRIVATE KEY-----
                """;
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.GITHUB_APP);
        properties.setAllowedRepositories(List.of("acme/order"));
        properties.setAppId("12345");
        properties.setInstallationId("98765");
        properties.setPrivateKeyRef(inlinePrivateKey);

        IllegalStateException exception = assertThrows(
                IllegalStateException.class,
                () -> new GitHubCodePlatformAdapter(properties, OBJECT_MAPPER, new RecordingSender(installationTokenResponse()))
                        .createPullRequest(command("acme", "order"))
        );

        assertTrue(exception.getMessage().contains("privateKeyRef"));
        assertFalse(exception.getMessage().contains("BEGIN RSA PRIVATE KEY"));
        assertFalse(exception.getMessage().contains("not-a-real-key"));
    }

    @Test
    void sourceShouldNotKnowFeishuTicketFields() throws IOException {
        String adapterSource = java.nio.file.Files.readString(moduleRoot().resolve(
                "src/main/java/com/wish/rd/bootstrap/github/GitHubCodePlatformAdapter.java"));

        assertFalse(adapterSource.toLowerCase().contains("feishu"));
        assertFalse(adapterSource.contains("helpdesk"));
        assertFalse(adapterSource.contains("ticketStatus"));
    }

    private static GitHubCodePlatformProperties realPatProperties() {
        GitHubCodePlatformProperties properties = new GitHubCodePlatformProperties();
        properties.setMode(GitHubCodePlatformProperties.Mode.REAL);
        properties.setAuthMode(GitHubCodePlatformProperties.AuthMode.PAT_LOCAL_SMOKE);
        properties.setApiBaseUrl("https://api.github.example.local");
        properties.setWebBaseUrl("https://github.example.local");
        properties.setPatToken("ghp-local-smoke");
        return properties;
    }

    private static CreatePullRequestCommand command(String owner, String repo) {
        return new CreatePullRequestCommand(
                owner,
                repo,
                "main",
                "repair/task-1001",
                "Fix order failure",
                "Generated by RD-Bot repair executor.",
                List.of(),
                Map.of("taskId", "task-1001")
        );
    }

    private static String successfulPullResponse() {
        return """
                {
                  "html_url": "https://github.example.local/acme/order/pull/42",
                  "number": 42,
                  "head": {"sha": "abc123"}
                }
                """;
    }

    private static String installationTokenResponse() {
        return """
                {
                  "token": "installation-token"
                }
                """;
    }

    private static String generatedPkcs1PrivateKeyPem() throws Exception {
        KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
        generator.initialize(2048);
        RSAPrivateCrtKey key = (RSAPrivateCrtKey) generator.generateKeyPair().getPrivate();
        byte[] pkcs1 = derSequence(
                derInteger(java.math.BigInteger.ZERO),
                derInteger(key.getModulus()),
                derInteger(key.getPublicExponent()),
                derInteger(key.getPrivateExponent()),
                derInteger(key.getPrimeP()),
                derInteger(key.getPrimeQ()),
                derInteger(key.getPrimeExponentP()),
                derInteger(key.getPrimeExponentQ()),
                derInteger(key.getCrtCoefficient())
        );
        return "-----BEGIN RSA PRIVATE KEY-----\n"
                + java.util.Base64.getMimeEncoder(64, "\n".getBytes(StandardCharsets.US_ASCII)).encodeToString(pkcs1)
                + "\n-----END RSA PRIVATE KEY-----\n";
    }

    private static byte[] derSequence(byte[]... entries) {
        int length = 0;
        for (byte[] entry : entries) {
            length += entry.length;
        }
        return derValue(0x30, concat(entries, length));
    }

    private static byte[] derInteger(java.math.BigInteger value) {
        return derValue(0x02, value.toByteArray());
    }

    private static byte[] derValue(int tag, byte[] body) {
        byte[] length = derLength(body.length);
        byte[] result = new byte[1 + length.length + body.length];
        result[0] = (byte) tag;
        System.arraycopy(length, 0, result, 1, length.length);
        System.arraycopy(body, 0, result, 1 + length.length, body.length);
        return result;
    }

    private static byte[] derLength(int length) {
        if (length < 128) {
            return new byte[]{(byte) length};
        }
        int bytes = 0;
        int value = length;
        while (value > 0) {
            bytes++;
            value >>= 8;
        }
        byte[] encoded = new byte[1 + bytes];
        encoded[0] = (byte) (0x80 | bytes);
        for (int index = bytes; index > 0; index--) {
            encoded[index] = (byte) (length & 0xff);
            length >>= 8;
        }
        return encoded;
    }

    private static byte[] concat(byte[][] entries, int length) {
        byte[] result = new byte[length];
        int offset = 0;
        for (byte[] entry : entries) {
            System.arraycopy(entry, 0, result, offset, entry.length);
            offset += entry.length;
        }
        return result;
    }

    private static java.nio.file.Path moduleRoot() {
        java.nio.file.Path current = java.nio.file.Path.of(System.getProperty("user.dir")).toAbsolutePath().normalize();
        if (current.getFileName() != null && "bootstrap".equals(current.getFileName().toString())) {
            return current;
        }
        return current.resolve("bootstrap");
    }

    private static final class RecordingSender implements GitHubCodePlatformAdapter.GitHubRequestSender {

        private final List<String> responseBodies;
        private final List<GitHubCodePlatformAdapter.GitHubHttpRequest> requests = new java.util.ArrayList<>();

        private RecordingSender(String... responseBodies) {
            this.responseBodies = List.of(responseBodies);
        }

        @Override
        public GitHubCodePlatformAdapter.GitHubHttpResponse send(GitHubCodePlatformAdapter.GitHubHttpRequest request) {
            int responseIndex = Math.min(requests.size(), responseBodies.size() - 1);
            requests.add(request);
            return new GitHubCodePlatformAdapter.GitHubHttpResponse(201, responseBodies.get(responseIndex));
        }

        private List<GitHubCodePlatformAdapter.GitHubHttpRequest> requests() {
            return List.copyOf(requests);
        }
    }

    @Configuration
    @Import({
            GitHubCodePlatformProperties.class,
            MockGitHubCodePlatformAdapter.class,
            GitHubCodePlatformAdapter.class
    })
    static class GitHubAdapterContextConfiguration {
    }
}
