package com.wish.rd.bootstrap;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Structured provider preflight evidence generated by {@link ProviderPreflightRealSmokeTest}.
 */
record ProviderPreflightEvidenceFile(
        boolean validated,
        int expectedProviderCount,
        int successfulProviderCount,
        List<String> providerNames
) {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    ProviderPreflightEvidenceFile {
        expectedProviderCount = Math.max(expectedProviderCount, 0);
        successfulProviderCount = Math.max(successfulProviderCount, 0);
        providerNames = providerNames == null ? List.of() : providerNames.stream()
                .map(ProviderPreflightEvidenceFile::safe)
                .filter(value -> !value.isBlank())
                .toList();
    }

    static ProviderPreflightEvidenceFile empty() {
        return new ProviderPreflightEvidenceFile(false, 0, 0, List.of());
    }

    static ProviderPreflightEvidenceFile from(MultiAgentProductionAcceptanceProfile profile) {
        if (profile == null || profile.providerPreflightEvidenceJson().isBlank()) {
            return empty();
        }
        Path path = Path.of(profile.providerPreflightEvidenceJson()).toAbsolutePath().normalize();
        if (!Files.isRegularFile(path)) {
            return empty();
        }
        try {
            JsonNode root = OBJECT_MAPPER.readTree(path.toFile());
            JsonNode providers = root.path("providers");
            int expectedProviderCount = root.path("expectedProviderCount").asInt(0);
            int successfulProviderCount = root.path("successfulProviderCount").asInt(0);
            List<String> providerNames = providerNames(providers);
            boolean sameRun = profile.rdBotVersion().equals(root.path("rdBotVersion").asText(""))
                    && profile.environmentId().equals(root.path("environmentId").asText(""))
                    && profile.executedBy().equals(root.path("executedBy").asText(""));
            long successfulProbeCount = providers.isArray()
                    ? java.util.stream.StreamSupport.stream(providers.spliterator(), false)
                            .filter(ProviderPreflightEvidenceFile::successfulProviderProbe)
                            .count()
                    : 0;
            boolean validated = root.path("providerPreflightEvidenceValidated").asBoolean(false)
                    && "PASSED_PROVIDER_PREFLIGHT_SMOKE".equals(root.path("conclusion").asText(""))
                    && sameRun
                    && expectedProviderCount >= profile.expectedProviderCount()
                    && successfulProviderCount >= profile.expectedProviderCount()
                    && providers.isArray()
                    && providerNames.stream().distinct().count() >= profile.expectedProviderCount()
                    && successfulProbeCount >= profile.expectedProviderCount();
            return validated
                    ? new ProviderPreflightEvidenceFile(
                            true,
                            expectedProviderCount,
                            successfulProviderCount,
                            providerNames
                    )
                    : empty();
        } catch (RuntimeException | java.io.IOException ignored) {
            return empty();
        }
    }

    int providerCount() {
        return providerNames.size();
    }

    private static List<String> providerNames(JsonNode providers) {
        if (!providers.isArray()) {
            return List.of();
        }
        java.util.ArrayList<String> names = new java.util.ArrayList<>();
        providers.forEach(provider -> {
            String name = safe(provider.path("name").asText(""));
            if (!name.isBlank()) {
                names.add(name);
            }
        });
        return List.copyOf(names);
    }

    private static boolean successfulProviderProbe(JsonNode provider) {
        return provider.path("success").asBoolean(false)
                && provider.path("httpStatus").asInt(0) >= 200
                && provider.path("httpStatus").asInt(0) < 300
                && !safe(provider.path("name").asText("")).isBlank()
                && supportedProtocol(provider.path("protocol").asText(""))
                && !safe(provider.path("adapterName").asText("")).isBlank()
                && isHttpUrl(provider.path("baseUrl").asText(""))
                && !safe(provider.path("apiKeyEnv").asText("")).isBlank()
                && !safe(provider.path("model").asText("")).isBlank();
    }

    private static boolean supportedProtocol(String value) {
        return switch (safe(value)) {
            case "anthropic-compatible", "anthropic-claude-code", "claude-code", "anthropic",
                    "openai-chat-completions" -> true;
            default -> false;
        };
    }

    private static boolean isHttpUrl(String value) {
        try {
            URI uri = URI.create(safe(value));
            String scheme = safe(uri.getScheme()).toLowerCase(java.util.Locale.ROOT);
            return ("http".equals(scheme) || "https".equals(scheme))
                    && !safe(uri.getHost()).isBlank();
        } catch (RuntimeException ignored) {
            return false;
        }
    }

    private static String safe(String value) {
        return value == null ? "" : value.strip();
    }
}
