package com.wish.rd.bootstrap;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Structured Skill policy evidence generated by {@link SkillPolicyRealSmokeTest}.
 */
record SkillPolicyEvidenceFile(
        boolean validated,
        String taskId,
        String stageRunId,
        String skillId,
        String skillVersion,
        String allowedRole,
        String rejectedRole,
        String highRiskRole,
        String installPath,
        String sourceChecksum,
        boolean installed,
        boolean unauthorizedRejected,
        boolean highRiskWaitingApproval,
        boolean metadataValidated,
        int installerCallCount
) {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    SkillPolicyEvidenceFile {
        taskId = safe(taskId);
        stageRunId = safe(stageRunId);
        skillId = safe(skillId);
        skillVersion = safe(skillVersion);
        allowedRole = safe(allowedRole);
        rejectedRole = safe(rejectedRole);
        highRiskRole = safe(highRiskRole);
        installPath = safe(installPath);
        sourceChecksum = safe(sourceChecksum);
        installerCallCount = Math.max(installerCallCount, 0);
    }

    static SkillPolicyEvidenceFile empty() {
        return new SkillPolicyEvidenceFile(
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                false,
                false,
                false,
                false,
                0
        );
    }

    static SkillPolicyEvidenceFile from(MultiAgentProductionAcceptanceProfile profile) {
        if (profile == null || profile.skillPolicyEvidenceJson().isBlank()) {
            return empty();
        }
        Path path = Path.of(profile.skillPolicyEvidenceJson()).toAbsolutePath().normalize();
        if (!Files.isRegularFile(path)) {
            return empty();
        }
        try {
            JsonNode root = OBJECT_MAPPER.readTree(path.toFile());
            int installerCallCount = root.path("installerCallCount").asInt(0);
            String skillId = root.path("skillId").asText("");
            String skillVersion = root.path("skillVersion").asText("");
            String installPath = root.path("installPath").asText("");
            String taskId = root.path("taskId").asText("");
            String skillPolicyTaskId = root.path("skillPolicyTaskId").asText("");
            boolean sameRun = profile.rdBotVersion().equals(root.path("rdBotVersion").asText(""))
                    && profile.environmentId().equals(root.path("environmentId").asText(""))
                    && profile.executedBy().equals(root.path("executedBy").asText(""));
            boolean validated = root.path("skillPolicyEvidenceValidated").asBoolean(false)
                    && sameRun
                    && !taskId.isBlank()
                    && taskId.equals(skillPolicyTaskId)
                    && !root.path("stageRunId").asText("").isBlank()
                    && !skillId.isBlank()
                    && !skillVersion.isBlank()
                    && !root.path("allowedRole").asText("").isBlank()
                    && !root.path("rejectedRole").asText("").isBlank()
                    && !root.path("highRiskRole").asText("").isBlank()
                    && distinctRoles(
                            root.path("allowedRole").asText(""),
                            root.path("rejectedRole").asText(""),
                            root.path("highRiskRole").asText(""))
                    && installPathMatchesSkillIdentity(installPath, skillId, skillVersion)
                    && sourceChecksumIsFullSha256(root.path("sourceChecksum").asText(""))
                    && root.path("installed").asBoolean(false)
                    && root.path("unauthorizedRejected").asBoolean(false)
                    && root.path("highRiskWaitingApproval").asBoolean(false)
                    && root.path("metadataValidated").asBoolean(false)
                    && installerCallCount == 1;
            return validated ? new SkillPolicyEvidenceFile(
                    true,
                    taskId,
                    root.path("stageRunId").asText(""),
                    skillId,
                    skillVersion,
                    root.path("allowedRole").asText(""),
                    root.path("rejectedRole").asText(""),
                    root.path("highRiskRole").asText(""),
                    installPath,
                    root.path("sourceChecksum").asText(""),
                    true,
                    true,
                    true,
                    true,
                    installerCallCount
            ) : empty();
        } catch (RuntimeException | java.io.IOException ignored) {
            return empty();
        }
    }

    MultiAgentProductionAcceptanceReport.SkillPolicyEvidence toReportEvidence() {
        if (!validated) {
            return MultiAgentProductionAcceptanceReport.SkillPolicyEvidence.empty();
        }
        return new MultiAgentProductionAcceptanceReport.SkillPolicyEvidence(
                true,
                taskId,
                stageRunId,
                skillId,
                skillVersion,
                allowedRole,
                rejectedRole,
                highRiskRole,
                installPath,
                sourceChecksum,
                installed,
                unauthorizedRejected,
                highRiskWaitingApproval,
                metadataValidated,
                installerCallCount
        );
    }

    private static String safe(String value) {
        return value == null ? "" : value.strip();
    }

    private static boolean installPathMatchesSkillIdentity(String installPath, String skillId, String skillVersion) {
        String safeInstallPath = safe(installPath);
        String safeSkillId = safe(skillId);
        String safeSkillVersion = safe(skillVersion);
        if (safeInstallPath.isBlank() || safeSkillId.isBlank() || safeSkillVersion.isBlank()) {
            return false;
        }
        try {
            Path normalizedInstallPath = Path.of(safeInstallPath).normalize();
            return normalizedInstallPath.isAbsolute()
                    && normalizedInstallPath.endsWith(Path.of(safeSkillId, safeSkillVersion));
        } catch (RuntimeException ignored) {
            return false;
        }
    }

    private static boolean distinctRoles(String allowedRole, String rejectedRole, String highRiskRole) {
        String allowed = safe(allowedRole);
        String rejected = safe(rejectedRole);
        String highRisk = safe(highRiskRole);
        return !allowed.equals(rejected)
                && !allowed.equals(highRisk)
                && !rejected.equals(highRisk);
    }

    private static boolean sourceChecksumIsFullSha256(String sourceChecksum) {
        return safe(sourceChecksum).matches("sha256:[0-9a-fA-F]{64}");
    }
}
