package com.wish.rd.bootstrap;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Structured workflow restart/recovery evidence generated by a production-equivalent rehearsal.
 */
record WorkflowRecoveryEvidenceFile(
        boolean validated,
        String taskId,
        int stageRunCountBeforeRestart,
        int stageRunCountAfterRestart,
        int stageEventCountBeforeRestart,
        int stageEventCountAfterRestart,
        int duplicateSuccessfulStageCount,
        int retryAttemptCount,
        int retainedRetryArtifactCount,
        boolean deliveryReviewApprovedBeforePrCreating,
        List<String> timelineStatuses,
        String startupLogEvidenceUri,
        String databaseSnapshotEvidenceUri
) {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
    private static final List<String> REQUIRED_TIMELINE_ORDER = List.of(
            "EXECUTING",
            "VALIDATING",
            "PR_CREATING",
            "COMMITTED",
            "REPORTING",
            "COMPLETED"
    );

    WorkflowRecoveryEvidenceFile {
        taskId = taskId == null ? "" : taskId.strip();
        stageRunCountBeforeRestart = Math.max(stageRunCountBeforeRestart, 0);
        stageRunCountAfterRestart = Math.max(stageRunCountAfterRestart, 0);
        stageEventCountBeforeRestart = Math.max(stageEventCountBeforeRestart, 0);
        stageEventCountAfterRestart = Math.max(stageEventCountAfterRestart, 0);
        duplicateSuccessfulStageCount = Math.max(duplicateSuccessfulStageCount, 0);
        retryAttemptCount = Math.max(retryAttemptCount, 0);
        retainedRetryArtifactCount = Math.max(retainedRetryArtifactCount, 0);
        timelineStatuses = timelineStatuses == null ? List.of() : List.copyOf(timelineStatuses);
        startupLogEvidenceUri = startupLogEvidenceUri == null ? "" : startupLogEvidenceUri.strip();
        databaseSnapshotEvidenceUri = databaseSnapshotEvidenceUri == null ? ""
                : databaseSnapshotEvidenceUri.strip();
    }

    static WorkflowRecoveryEvidenceFile empty() {
        return new WorkflowRecoveryEvidenceFile(
                false,
                "",
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                false,
                List.of(),
                "",
                ""
        );
    }

    static WorkflowRecoveryEvidenceFile from(MultiAgentProductionAcceptanceProfile profile) {
        if (profile == null || profile.recoveryEvidenceJson().isBlank()) {
            return empty();
        }
        Path path = Path.of(profile.recoveryEvidenceJson()).toAbsolutePath().normalize();
        if (!Files.isRegularFile(path)) {
            return empty();
        }
        try {
            JsonNode root = OBJECT_MAPPER.readTree(path.toFile());
            List<String> timelineStatuses = values(root.path("timelineStatuses"));
            String startupLogEvidenceUri = root.path("startupLogEvidenceUri").asText("");
            String databaseSnapshotEvidenceUri = root.path("databaseSnapshotEvidenceUri").asText("");
            int stageRunCountBeforeRestart = root.path("stageRunCountBeforeRestart").asInt(0);
            int stageRunCountAfterRestart = root.path("stageRunCountAfterRestart").asInt(0);
            int stageEventCountBeforeRestart = root.path("stageEventCountBeforeRestart").asInt(0);
            int stageEventCountAfterRestart = root.path("stageEventCountAfterRestart").asInt(0);
            int duplicateSuccessfulStageCount = root.path("duplicateSuccessfulStageCount").asInt(-1);
            int retryAttemptCount = root.path("retryAttemptCount").asInt(0);
            int retainedRetryArtifactCount = root.path("retainedRetryArtifactCount").asInt(0);
            String taskId = root.path("taskId").asText("");
            String recoveryTaskId = root.path("recoveryTaskId").asText("");
            boolean sameRun = profile.rdBotVersion().equals(root.path("rdBotVersion").asText(""))
                    && profile.environmentId().equals(root.path("environmentId").asText(""))
                    && profile.executedBy().equals(root.path("executedBy").asText(""));
            boolean validated = root.path("workflowRecoveryEvidenceValidated").asBoolean(false)
                    && sameRun
                    && !taskId.isBlank()
                    && taskId.equals(recoveryTaskId)
                    && stageRunCountBeforeRestart > 0
                    && stageRunCountAfterRestart >= 4
                    && stageRunCountAfterRestart >= stageRunCountBeforeRestart
                    && stageEventCountBeforeRestart > 0
                    && stageEventCountAfterRestart >= stageEventCountBeforeRestart
                    && duplicateSuccessfulStageCount == 0
                    && retryAttemptCount >= 0
                    && retainedRetryArtifactCount >= 0
                    && root.path("deliveryReviewApprovedBeforePrCreating").asBoolean(false)
                    && containsInOrder(timelineStatuses, REQUIRED_TIMELINE_ORDER)
                    && productionEvidenceUri(startupLogEvidenceUri)
                    && productionEvidenceUri(databaseSnapshotEvidenceUri);
            return validated ? new WorkflowRecoveryEvidenceFile(
                    true,
                    taskId,
                    stageRunCountBeforeRestart,
                    stageRunCountAfterRestart,
                    stageEventCountBeforeRestart,
                    stageEventCountAfterRestart,
                    duplicateSuccessfulStageCount,
                    retryAttemptCount,
                    retainedRetryArtifactCount,
                    true,
                    timelineStatuses,
                    startupLogEvidenceUri,
                    databaseSnapshotEvidenceUri
            ) : empty();
        } catch (RuntimeException | java.io.IOException ignored) {
            return empty();
        }
    }

    MultiAgentProductionAcceptanceReport.WorkflowRecoveryEvidence toReportEvidence() {
        if (!validated) {
            return MultiAgentProductionAcceptanceReport.WorkflowRecoveryEvidence.empty();
        }
        return new MultiAgentProductionAcceptanceReport.WorkflowRecoveryEvidence(
                true,
                taskId,
                stageRunCountBeforeRestart,
                stageRunCountAfterRestart,
                stageEventCountBeforeRestart,
                stageEventCountAfterRestart,
                duplicateSuccessfulStageCount,
                retryAttemptCount,
                retainedRetryArtifactCount,
                deliveryReviewApprovedBeforePrCreating,
                timelineStatuses,
                startupLogEvidenceUri,
                databaseSnapshotEvidenceUri
        );
    }

    private static List<String> values(JsonNode node) {
        if (!node.isArray()) {
            return List.of();
        }
        java.util.ArrayList<String> values = new java.util.ArrayList<>();
        node.forEach(item -> {
            String value = item.asText("").strip();
            if (!value.isBlank()) {
                values.add(value);
            }
        });
        return List.copyOf(values);
    }

    private static boolean containsInOrder(List<String> actual, List<String> expected) {
        return containsOrderedSubsequence(actual, expected) && firstOccurrencesInOrder(actual, expected);
    }

    private static boolean containsOrderedSubsequence(List<String> actual, List<String> expected) {
        int cursor = 0;
        for (String status : actual) {
            if (cursor < expected.size() && expected.get(cursor).equals(status)) {
                cursor++;
            }
        }
        return cursor == expected.size();
    }

    private static boolean firstOccurrencesInOrder(List<String> actual, List<String> expected) {
        int previous = -1;
        for (String status : expected) {
            int current = actual.indexOf(status);
            if (current <= previous) {
                return false;
            }
            previous = current;
        }
        return true;
    }

    private static boolean productionEvidenceUri(String value) {
        return ProductionEvidenceUris.isProductionArtifactUri(value);
    }
}
